theme: jekyll-theme-minimal
title: 价值理念：塑造超级个体
logo: /avatar.jpg  # 添加这一行
description: >
  通过不断自我超越、达到高远的自由，达成逍遥游的境界 (Pursuing ture excellence) —— 《庄子·逍遥游》
  <br><br>
  <b>快速导航</b><br>
  • <a href="./goals.html">年度目标</a><br>
  • <a href="./weekly/">潮流周刊</a><br>
  • <a href="./about.html">关于我</a><br>
  <br><br>
<img src="https://img.shields.io/badge/Focus-AI%20Automation-blue">
<img src="https://img.shields.io/badge/Goal-PhD%202027-green">
